name: docker-qiandao
on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 06 * * *' 
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天0点0分（24点整）
    # 建议每个人通过设置 GitHub Environments 的方式来设定为自己的目标运行时间（详细设置方法见文档说明）
    

jobs:    



  AutoDownloaderProcess:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.1.0
        # 输出IP
    - name: IP
      run: sudo curl ifconfig.me
        
       
    - name: docker install
      run: curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
    - name: docker run  (yuanshen)
      run: |
            docker run --restart=on-failure --name soga-2 -d \
            -v /etc/soga/2/:/etc/soga/ --network host \
            -e type=v2board \
            -e server_type=v2ray \
            -e api=webapi \
            -e webapi_url=http://v2.winkx.ga \
            -e webapi_key=wink000117djq991211 \
            -e node_id=31 \
            -e user_conn_limit=0 \
            -e user_speed_limit=0 \
            sprov065/soga
 
